// packages/extension/src/ui/primitives/alert.tsx
import * as React from "react";
import { type VariantProps } from "class-variance-authority";
import { cn } from "../util/cn";
import { alertVariants } from "./alert-variants";

const Alert = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement> & VariantProps<typeof alertVariants>
>(({ className, variant, ...props }, ref) => (
  <div
    ref={ref}
    role="alert"
    className={cn(alertVariants({ variant }), className)}
    {...props}
  />
));
Alert.displayName = "Alert";

const AlertTitle = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLHeadingElement>
>(({ className, ...props }, ref) => (
  <h5
    ref={ref}
    className={cn("mb-1 font-medium leading-none tracking-tight", className)}
    {...props}
  />
));
AlertTitle.displayName = "AlertTitle";

const AlertDescription = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn("text-sm [&_p]:leading-relaxed", className)}
    {...props}
  />
));
AlertDescription.displayName = "AlertDescription";

export { Alert, AlertTitle, AlertDescription };

// packages/extension/src/ui-solid/primitives/alert.tsx
/** @jsxImportSource solid-js */
import { type VariantProps } from "class-variance-authority";
import { type ComponentProps, splitProps } from "solid-js";
import { cn } from "../util/cn";
import { alertVariants } from "./alert-variants";

export interface AlertProps
  extends ComponentProps<"div">,
    VariantProps<typeof alertVariants> {}

export const Alert = (props: AlertProps) => {
  const [local, others] = splitProps(props, ["variant", "class"]);
  
  return (
    <div
      role="alert"
      class={cn(alertVariants({ variant: local.variant }), local.class)}
      {...others}
    />
  );
};

export interface AlertTitleProps extends ComponentProps<"h5"> {}

export const AlertTitle = (props: AlertTitleProps) => {
  const [local, others] = splitProps(props, ["class"]);
  
  return (
    <h5
      class={cn("mb-1 font-medium leading-none tracking-tight", local.class)}
      {...others}
    />
  );
};

export interface AlertDescriptionProps extends ComponentProps<"div"> {}

export const AlertDescription = (props: AlertDescriptionProps) => {
  const [local, others] = splitProps(props, ["class"]);
  
  return (
    <div
      class={cn("text-sm [&_p]:leading-relaxed", local.class)}
      {...others}
    />
  );
};
