// packages/extension/src/ui/primitives/checkbox.tsx
import * as React from "react";
import * as CheckboxPrimitive from "@radix-ui/react-checkbox";
import { Check } from "lucide-react";
import { cn } from "../util/cn";

const Checkbox = React.forwardRef<
  React.ElementRef<typeof CheckboxPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof CheckboxPrimitive.Root>
>(({ className, ...props }, ref) => (
  <CheckboxPrimitive.Root
    ref={ref}
    className={cn(
      "peer h-4 w-4 shrink-0 rounded-sm border border-primary shadow focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground",
      className
    )}
    {...props}
  >
    <CheckboxPrimitive.Indicator
      className={cn("flex items-center justify-center text-current")}
    >
      <Check className="h-4 w-4" />
    </CheckboxPrimitive.Indicator>
  </CheckboxPrimitive.Root>
));
Checkbox.displayName = CheckboxPrimitive.Root.displayName;

export { Checkbox };

// packages/extension/src/ui-solid/primitives/checkbox.tsx
/** @jsxImportSource solid-js */
import { Checkbox as CheckboxPrimitive } from "@kobalte/core/checkbox";
import { Check } from "lucide-solid";
import { type ComponentProps, splitProps } from "solid-js";
import { cn } from "../util/cn";

export interface CheckboxProps extends ComponentProps<typeof CheckboxPrimitive> {
  class?: string;
}

export const Checkbox = (props: CheckboxProps) => {
  const [local, others] = splitProps(props, ["class"]);
  
  return (
    <CheckboxPrimitive
      class={cn(
        "peer h-4 w-4 shrink-0 rounded-sm border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[checked]:bg-primary data-[checked]:text-primary-foreground",
        local.class
      )}
      {...others}
    >
      <CheckboxPrimitive.Indicator class="flex items-center justify-center text-current">
        <Check class="h-4 w-4" />
      </CheckboxPrimitive.Indicator>
    </CheckboxPrimitive>
  );
};
